# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MorphoShaper
                                 A QGIS plugin
 Make morphological preprocessing for raster data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-06
        copyright            : (C) 2025 by Aital/HighlandGold
        email                : unaait@mail.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MorphoShaper class from file MorphoShaper.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .morphology_shaper import MorphoShaper
    return MorphoShaper(iface)
